// 预编译头文件
#include <sstream>
#include <iostream>
#include <string>
#include <functional>
#include <memory>
#include <cassert>
#include <cstdlib>
#include <vector>
#include <array>
#include <algorithm>
