#pragma once

namespace MOUSE
{

// From ALICE3.h
#define ALICE_MOUSE_BUTTON_1         0
#define ALICE_MOUSE_BUTTON_2         1
#define ALICE_MOUSE_BUTTON_3         2
#define ALICE_MOUSE_BUTTON_4         3
#define ALICE_MOUSE_BUTTON_5         4
#define ALICE_MOUSE_BUTTON_6         5
#define ALICE_MOUSE_BUTTON_7         6
#define ALICE_MOUSE_BUTTON_8         7
#define ALICE_MOUSE_BUTTON_LAST      ALICE_MOUSE_BUTTON_8
#define ALICE_MOUSE_BUTTON_LEFT      ALICE_MOUSE_BUTTON_1
#define ALICE_MOUSE_BUTTON_RIGHT     ALICE_MOUSE_BUTTON_2
#define ALICE_MOUSE_BUTTON_MIDDLE    ALICE_MOUSE_BUTTON_3

} // namespace MOUSE
